using System.Diagnostics;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.Entities.Creatures;
using MegaCrit.Sts2.Core.Entities.Players;
using MegaCrit.Sts2.Core.Models;

namespace CoopBots.Kernel;

/// <summary>
/// Team policy supplies a score; the imported engine owns all card effects.
/// Advance must run on the capturing game thread while the live root is stable.
/// A slice ends between actions: one native effect cannot be preempted.
/// </summary>
public sealed class KernelTeamSearch : IDisposable
{
    // Exactly one of Card/Potion/EndTurn is set. Potions are free actions, so the search
    // can discover "use a buff potion, then play the burst" as one plan.
    public sealed record Action(Player Player, CardModel? Card, Creature? Target, PotionModel? Potion = null,
        IReadOnlyList<KernelChoice>? Choices = null, bool EndTurn = false);
    public sealed record Options(int Depth = 9, int Width = 12, int MaxNodes = 512, bool IncludeEndTurns = false,
        int MaxRounds = 2);
    public sealed record Result(IReadOnlyList<Action> Actions, double Score, int ExpandedNodes,
        IReadOnlyDictionary<string, int> Boundaries, string StopReason, bool HasUncertainRisk);
    private sealed record Node(KernelSession State, Action[] Path, double Score, bool Risky);
    private readonly int thread = Environment.CurrentManagedThreadId;
    private readonly Player[] actors;
    private readonly Func<KernelSession, double> evaluate;
    private readonly Options options;
    private readonly Dictionary<string, int> boundaries = new(StringComparer.Ordinal);
    private readonly IEnumerator<bool> steps;
    private Node best;
    private Node? bestResolved;
    private int expanded;
    private bool disposed;
    public bool IsComplete { get; private set; }
    public Result? CompletedResult { get; private set; }
    public KernelSession? CompletedState { get; private set; }

    public KernelTeamSearch(KernelSession root, IEnumerable<Player> actors,
        Func<KernelSession, double> evaluate, Options? options = null)
    {
        this.options = options ?? new();
        if (this.options.Depth < 1 || this.options.Width < 1 || this.options.MaxNodes < 1)
            throw new ArgumentOutOfRangeException(nameof(options));
        this.actors = actors.Distinct().ToArray();
        this.evaluate = evaluate;
        // Own the root: callers cannot mutate a running search through their session.
        var owned = root.Fork();
        best = new(owned, [], Score(owned), false);
        steps = Expand(best).GetEnumerator();
    }

    public bool Advance(TimeSpan slice, Func<bool> rootStillCurrent, CancellationToken cancellation = default)
    {
        ObjectDisposedException.ThrowIf(disposed, this);
        if (Environment.CurrentManagedThreadId != thread)
            throw new InvalidOperationException("Kernel search must stay on its capturing thread.");
        if (IsComplete) return true;
        if (slice <= TimeSpan.Zero) throw new ArgumentOutOfRangeException(nameof(slice));
        if (cancellation.IsCancellationRequested || !rootStillCurrent())
        { Cancel(cancellation.IsCancellationRequested ? "cancelled" : "stale-root"); return true; }
        var watch = Stopwatch.StartNew();
        do
        {
            if (cancellation.IsCancellationRequested) { Cancel("cancelled"); return true; }
            if (!steps.MoveNext()) { Complete(expanded >= options.MaxNodes ? "node-budget" : "depth-or-exhausted"); return true; }
        } while (watch.Elapsed < slice);
        return false;
    }

    private IEnumerable<bool> Expand(Node root)
    {
        var frontier = new List<Node> { root };
        for (var depth = 0; depth < options.Depth && frontier.Count > 0; depth++)
        {
            var next = new List<Node>();
            foreach (var parent in frontier)
            foreach (var actor in actors)
            {
                if (!parent.State.CanAct(actor) || parent.State.Enemies.Count == 0) continue;
                // Enumerate each branch hand, including cards drawn/generated by earlier bots.
                foreach (var card in parent.State.Hand(actor))
                {
                    if (!parent.State.CanPlay(card)) continue;
                    foreach (var target in parent.State.Targets(card))
                    foreach (var branch in parent.State.CardBranches(card, target, Math.Min(8, options.MaxNodes - expanded)))
                    {
                        if (expanded >= options.MaxNodes) yield break;
                        expanded++;
                        var child = branch.State;
                        var boundary = branch.Boundary;
                        if (boundary.Length == 0 && branch.Choices.Any(c => !actors.Any(p => p.NetId == c.Owner)))
                            boundary = "external-player-choice";
                        if (boundary.Length > 0)
                        {
                            var key = card.Id.Entry + ":" + boundary;
                            boundaries[key] = boundaries.GetValueOrDefault(key) + 1;
                            yield return true;
                            continue;
                        }
                        var node = new Node(child, [.. parent.Path, new(actor, card, target, Choices: branch.Choices)], Score(child),
                            parent.Risky || child.LastActionHadEnvironmentalRisk);
                        if (node.Score > best.Score) best = node;
                        if ((child.HasWon || child.EnemyPhaseCompleted) && (bestResolved is null || node.Score > bestResolved.Score)) bestResolved = node;
                        next.Add(node);
                        // Bound retained memory throughout expansion, not just at end of depth.
                        if (next.Count > options.Width * 4)
                            next = next.OrderByDescending(n => n.Score).Take(options.Width).ToList();
                        yield return true;
                    }
                }
                // Free potion actions. A potion that cannot be simulated in this
                // branch is simply skipped (potions are optional, unlike cards).
                foreach (var potion in parent.State.UsablePotions(actor))
                foreach (var target in parent.State.PotionTargets(potion))
                {
                    if (expanded >= options.MaxNodes) yield break;
                    expanded++;
                    var child = parent.State.Fork();
                    if (!child.UsePotion(potion, target, out _))
                    {
                        yield return true;
                        continue;
                    }
                    var node = new Node(child, [.. parent.Path, new(actor, null, target, potion)], Score(child),
                        parent.Risky || child.LastActionHadEnvironmentalRisk);
                    if (node.Score > best.Score) best = node;
                    if (child.HasWon && (bestResolved is null || node.Score > bestResolved.Score)) bestResolved = node;
                    next.Add(node);
                    if (next.Count > options.Width * 4)
                        next = next.OrderByDescending(n => n.Score).Take(options.Width).ToList();
                    yield return true;
                }
                if (options.IncludeEndTurns)
                {
                    if (expanded >= options.MaxNodes) yield break;
                    expanded++;
                    var child = parent.State.Fork();
                    if (child.EndTurn(actor, options.MaxRounds, out var boundary))
                    {
                        var node = new Node(child, [.. parent.Path, new(actor, null, null, EndTurn: true)], Score(child),
                            parent.Risky || child.LastActionHadEnvironmentalRisk);
                        if (node.Score > best.Score) best = node;
                        if (child.EnemyPhaseCompleted)
                        {
                            if (bestResolved is null || node.Score > bestResolved.Score) bestResolved = node;
                        }
                        else
                        {
                            next.Add(node);
                        }
                    }
                    else boundaries["end-turn:" + boundary] = boundaries.GetValueOrDefault("end-turn:" + boundary) + 1;
                    yield return true;
                }
            }
            // Dedup equivalent states, then keep a diverse frontier: one attack,
            // skill/block, potion and end-turn line each before filling by score.
            // A pure top-score cut can otherwise exhaust the budget on variations
            // of one idea and never compare a defense or a settling line.
            frontier = SelectFrontier(next, options.Width);
        }
    }
    // Drop exact-equivalent states (same compact key, keeping the better score),
    // then keep one line per action category before filling by score.
    private static List<Node> SelectFrontier(List<Node> candidates, int width)
    {
        var best = new Dictionary<string, Node>(StringComparer.Ordinal);
        foreach (var node in candidates.OrderByDescending(n => n.Score))
            if (!best.TryGetValue(node.State.CompactStateKey(), out var kept) || node.Score > kept.Score)
                best[node.State.CompactStateKey()] = node;
        var deduped = best.Values.OrderByDescending(n => n.Score).ToList();
        var chosen = new List<Node>();
        var used = new HashSet<Node>();
        foreach (var category in new[] { "attack", "skill", "power", "potion", "endturn", "other" })
        {
            if (chosen.Count >= width) break;
            var pick = deduped.FirstOrDefault(n => Category(n) == category && !used.Contains(n));
            if (pick is not null && used.Add(pick)) chosen.Add(pick);
        }
        foreach (var node in deduped)
        {
            if (chosen.Count >= width) break;
            if (used.Add(node)) chosen.Add(node);
        }
        return chosen.OrderByDescending(n => n.Score).Take(width).ToList();
    }

    private static string Category(Node node)
    {
        if (node.Path.Length == 0) return "other";
        var action = node.Path[^1];
        if (action.EndTurn) return "endturn";
        if (action.Potion is not null) return "potion";
        return action.Card?.Type switch
        {
            CardType.Attack => "attack",
            CardType.Skill => "skill",
            CardType.Power => "power",
            _ => "other",
        };
    }

    private double Score(KernelSession state)
    {
        var score = evaluate(state);
        if (!double.IsFinite(score)) throw new InvalidOperationException("Team score must be finite.");
        return score;
    }
    private void Complete(string reason)
    {
        // Prefer a settled plan, but never adopt one that scores worse than an
        // unsettled alternative: settled and projected scores are not identical.
        if (reason is not ("cancelled" or "stale-root") && bestResolved is not null && bestResolved.Score >= best.Score)
            best = bestResolved;
        IsComplete = true;
        CompletedState = reason is "cancelled" or "stale-root" ? null : best.State;
        CompletedResult = new(Array.AsReadOnly(best.Path), best.Score, expanded,
            new System.Collections.ObjectModel.ReadOnlyDictionary<string, int>(new Dictionary<string, int>(boundaries)), reason,
            best.Risky);
        steps.Dispose();
    }
    private void Cancel(string reason)
    {
        // A stale/cancelled plan must not retain even its first deployment action.
        best = best with { Path = [] };
        Complete(reason);
    }
    public void FinishAtBudget()
    {
        ObjectDisposedException.ThrowIf(disposed, this);
        if (Environment.CurrentManagedThreadId != thread) throw new InvalidOperationException("Wrong search thread.");
        if (!IsComplete) Complete("time-budget");
    }
    public void Dispose() { if (disposed) return; steps.Dispose(); disposed = true; }
}
