// <auto-generated>
//     Generated by scripts/import-spire-codex-events.py from
//     https://spire-codex.com/api/events
//
//     Source data: (c) 2025-present Peter Lord and Spire Codex contributors,
//     used under the PolyForm Noncommercial License 1.0.0 and the Spire
//     Codex API terms (community use, non-commercial, attribution
//     encouraged). Slay the Spire 2 game data belongs to Mega Crit Games.
//     See THIRD_PARTY_NOTICES.md. Do not edit by hand.
//
//     Option ids only: titles and descriptions are localized text and no
//     decision may depend on parsing them.
// </auto-generated>

namespace CoopBots.Building;

/// <summary>
/// Every option id each event can show, across all of its pages. Used to
/// check that the ids our handlers match still exist: a renamed id would
/// otherwise leave a handler silently dead.
/// </summary>
internal static class BakedEvents
{
    internal const string Source = "https://spire-codex.com/api/events";

    internal static readonly Dictionary<string, string[]> OptionIds = new(StringComparer.Ordinal)
    {
        ["ABYSSAL_BATHS"] = ["ABSTAIN", "EXIT_BATHS", "IMMERSE", "LINGER"],
        ["AMALGAMATOR"] = ["COMBINE_DEFENDS", "COMBINE_STRIKES"],
        ["AROMA_OF_CHAOS"] = ["LET_GO", "MAINTAIN_CONTROL"],
        ["BATTLEWORN_DUMMY"] = ["SETTING_1", "SETTING_2", "SETTING_3"],
        ["BRAIN_LEECH"] = ["RIP", "SHARE_KNOWLEDGE"],
        ["BUGSLAYER"] = ["EXTERMINATION", "SQUASH"],
        ["BYRDONIS_NEST"] = ["EAT", "TAKE"],
        ["COLORFUL_PHILOSOPHERS"] = ["DEFECT", "IRONCLAD", "NECROBINDER", "REGENT", "SILENT"],
        ["COLOSSAL_FLOWER"] = ["EXTRACT_CURRENT_PRIZE_1", "EXTRACT_CURRENT_PRIZE_2", "EXTRACT_INSTEAD", "POLLINOUS_CORE", "REACH_DEEPER_1", "REACH_DEEPER_2"],
        ["CRYSTAL_SPHERE"] = ["PAYMENT_PLAN", "UNCOVER_FUTURE"],
        ["DENSE_VEGETATION"] = ["FIGHT", "REST", "TRUDGE_ON"],
        ["DOLL_ROOM"] = ["EXAMINE", "RANDOM", "TAKE", "TAKE_SOME_TIME"],
        ["DOORS_OF_LIGHT_AND_DARK"] = ["DARK", "LIGHT"],
        ["DROWNING_BEACON"] = ["BOTTLE", "CLIMB"],
        ["ENDLESS_CONVEYOR"] = ["CAVIAR", "CLAM_ROLL", "FRIED_EEL", "GOLDEN_FYSH", "JELLY_LIVER", "LEAVE", "LOCKED", "OBSERVE_CHEF", "SEAPUNK_SALAD", "SPICY_SNAPPY", "SUSPICIOUS_CONDIMENT"],
        ["FIELD_OF_MAN_SIZED_HOLES"] = ["ENTER_YOUR_HOLE", "RESIST"],
        ["GRAVE_OF_THE_FORGOTTEN"] = ["ACCEPT", "CONFRONT", "CONFRONT_LOCKED"],
        ["HUNGRY_FOR_MUSHROOMS"] = ["BIG_MUSHROOM", "FRAGRANT_MUSHROOM"],
        ["INFESTED_AUTOMATON"] = ["STUDY", "TOUCH_CORE"],
        ["JUNGLE_MAZE_ADVENTURE"] = ["JOIN_FORCES", "SOLO_QUEST"],
        ["LOST_WISP"] = ["CLAIM", "SEARCH"],
        ["LUMINOUS_CHOIR"] = ["OFFER_TRIBUTE", "OFFER_TRIBUTE_LOCKED", "REACH_INTO_THE_FLESH"],
        ["MORPHIC_GROVE"] = ["GROUP", "LONER"],
        ["POTION_COURIER"] = ["GRAB_POTIONS", "RANSACK"],
        ["PUNCH_OFF"] = ["FIGHT", "I_CAN_TAKE_THEM", "NAB"],
        ["RANWID_THE_ELDER"] = ["GOLD", "POTION", "POTION_LOCKED", "RELIC", "RELIC_LOCKED"],
        ["REFLECTIONS"] = ["SHATTER", "TOUCH_A_MIRROR"],
        ["RELIC_TRADER"] = ["BOTTOM", "MIDDLE", "TOP"],
        ["ROOM_FULL_OF_CHEESE"] = ["GORGE", "SEARCH"],
        ["ROUND_TEA_PARTY"] = ["CONTINUE_FIGHT", "ENJOY_TEA", "PICK_FIGHT"],
        ["SAPPHIRE_SEED"] = ["EAT", "PLANT"],
        ["SELF_HELP_BOOK"] = ["NO_OPTIONS", "READ_ENTIRE_BOOK", "READ_ENTIRE_BOOK_LOCKED", "READ_PASSAGE", "READ_PASSAGE_LOCKED", "READ_THE_BACK", "READ_THE_BACK_LOCKED"],
        ["SLIPPERY_BRIDGE"] = ["HOLD_ON_0", "HOLD_ON_1", "HOLD_ON_2", "HOLD_ON_3", "HOLD_ON_4", "HOLD_ON_5", "HOLD_ON_6", "HOLD_ON_LOOP", "OVERCOME"],
        ["SPIRALING_WHIRLPOOL"] = ["DRINK", "OBSERVE"],
        ["SPIRIT_GRAFTER"] = ["LET_IT_IN", "REJECTION"],
        ["STONE_OF_ALL_TIME"] = ["LIFT", "LIFT_LOCKED", "PUSH", "PUSH_LOCKED"],
        ["SUNKEN_STATUE"] = ["DIVE_INTO_WATER", "GRAB_SWORD"],
        ["SUNKEN_TREASURY"] = ["FIRST_CHEST", "SECOND_CHEST"],
        ["SYMBIOTE"] = ["APPROACH", "APPROACH_LOCKED", "KILL_WITH_FIRE"],
        ["TABLET_OF_TRUTH"] = ["DECIPHER", "DECIPHER_1", "GIVE_UP", "SMASH"],
        ["TEA_MASTER"] = ["BONE_TEA", "BONE_TEA_LOCKED", "EMBER_TEA", "EMBER_TEA_LOCKED", "TEA_OF_DISCOURTESY"],
        ["THE_FUTURE_OF_POTIONS"] = ["POTION"],
        ["THE_LANTERN_KEY"] = ["FIGHT", "KEEP_THE_KEY", "RETURN_THE_KEY"],
        ["THE_LEGENDS_WERE_TRUE"] = ["NAB_THE_MAP", "SLOWLY_FIND_AN_EXIT"],
        ["THIS_OR_THAT"] = ["ORNATE", "PLAIN"],
        ["TINKER_TIME"] = ["ATTACK", "CHAOS", "CHOKING", "CHOOSE_CARD_TYPE", "CURIOUS", "ENERGIZED", "EXPERTISE", "IMPROVEMENT", "POWER", "SAPPING", "SKILL", "VIOLENCE", "WISDOM"],
        ["TRASH_HEAP"] = ["DIVE_IN", "GRAB"],
        ["TRIAL"] = ["ACCEPT", "DOUBLE_DOWN", "GUILTY", "INNOCENT", "REJECT"],
        ["UNREST_SITE"] = ["KILL", "REST"],
        ["WAR_HISTORIAN_REPY"] = ["UNLOCK_CAGE", "UNLOCK_CHEST"],
        ["WATERLOGGED_SCRIPTORIUM"] = ["BLOODY_INK", "PRICKLY_SPONGE", "PRICKLY_SPONGE_LOCKED", "TENTACLE_QUILL", "TENTACLE_QUILL_LOCKED"],
        ["WELCOME_TO_WONGOS"] = ["BARGAIN_BIN", "BARGAIN_BIN_LOCKED", "FEATURED_ITEM", "FEATURED_ITEM_LOCKED", "LEAVE", "MYSTERY_BOX", "MYSTERY_BOX_LOCKED"],
        ["WELLSPRING"] = ["BATHE", "BOTTLE"],
        ["WHISPERING_HOLLOW"] = ["GOLD", "HUG"],
        ["WOOD_CARVINGS"] = ["BIRD", "SNAKE", "SNAKE_LOCKED", "TORUS"],
        ["ZEN_WEAVER"] = ["ARACHNID_ACUPUNCTURE", "BREATHING_TECHNIQUES", "EMOTIONAL_AWARENESS", "LOCKED"],
    };
}
