// <auto-generated>
//     Generated by scripts/import-spire-codex-archetypes.py from
//     https://spire-codex.com/api/runs/archetypes
//     snapshot built_at=2026-08-22T21:38:23Z
//
//     Source data: (c) 2025-present Peter Lord and Spire Codex contributors,
//     used under the PolyForm Noncommercial License 1.0.0 and the Spire
//     Codex API terms (community use, non-commercial, attribution
//     encouraged). Slay the Spire 2 game data belongs to Mega Crit Games.
//     See THIRD_PARTY_NOTICES.md. Do not edit by hand.
// </auto-generated>

namespace CoopBots.Building;

/// <summary>
/// Archetype clusters mined from real runs, keyed by character. A cluster is
/// its signature: the cards that most distinguish it. Nothing here is
/// hand-authored, and the reported win rate is deliberately not carried
/// over because its scale is not consistent between clusters.
/// </summary>
internal static class BakedArchetypes
{
    internal const string Source = "https://spire-codex.com/api/runs/archetypes";
    internal const string Snapshot = "2026-08-22T21:38:23Z";

    internal sealed record Cluster(string Character, string Name, string[] Cards, string[] Relics, int Size);

    internal static readonly Cluster[] All =
    [
        new("IRONCLAD", "Bloodletting + Breakthrough", ["BLOODLETTING", "BREAKTHROUGH", "INFERNO"], ["CURSED_PEARL", "SWORD_OF_STONE"], 18323),
        new("IRONCLAD", "Feel No Pain + Mad Science", ["FEEL_NO_PAIN", "MAD_SCIENCE", "STOKE"], ["FRAGRANT_MUSHROOM", "PAELS_BLOOD"], 17577),
        new("IRONCLAD", "Iron Wave + Shrug It Off", ["IRON_WAVE", "SHRUG_IT_OFF", "ARMAMENTS"], ["FRESNEL_LENS", "SWORD_OF_STONE"], 17188),
        new("IRONCLAD", "Dominate + Mad Science", ["DOMINATE", "MAD_SCIENCE", "BULLY"], ["FRAGRANT_MUSHROOM", "NUTRITIOUS_SOUP"], 15124),
        new("IRONCLAD", "Molten Fist + Tremble", ["MOLTEN_FIST", "TREMBLE", "BULLY"], ["SWORD_OF_STONE", "SCROLL_BOXES"], 13065),
        new("IRONCLAD", "Perfected Strike + Hellraiser", ["PERFECTED_STRIKE", "HELLRAISER", "SETUP_STRIKE"], ["SWORD_OF_STONE", "LARGE_CAPSULE"], 12197),
        new("IRONCLAD", "Perfected Strike + Hellraiser", ["PERFECTED_STRIKE", "HELLRAISER", "TWIN_STRIKE"], ["FAKE_STRIKE_DUMMY", "NUTRITIOUS_SOUP"], 11937),
        new("IRONCLAD", "Break + Bully", ["BREAK", "BULLY", "DOMINATE"], ["ARCHAIC_TOOTH", "MERCURY_HOURGLASS"], 8480),
        new("IRONCLAD", "Maul + Mad Science", ["MAUL", "MAD_SCIENCE", "DARK_EMBRACE"], ["CLAWS", "MEAT_CLEAVER"], 7101),
        new("IRONCLAD", "Crimson Mantle + Hemokinesis", ["CRIMSON_MANTLE", "HEMOKINESIS", "INFERNO"], ["TOUCH_OF_OROBAS", "PEAR"], 5763),
        new("IRONCLAD", "Byrd Swoop + Pyre", ["BYRD_SWOOP", "PYRE", "DISMANTLE"], ["BYRDPIP", "ORNAMENTAL_FAN"], 3777),
        new("IRONCLAD", "Forgotten Ritual + Havoc", ["FORGOTTEN_RITUAL", "HAVOC", "PRIMAL_FORCE"], ["PANDORAS_BOX", "REPTILE_TRINKET"], 3204),
        new("SILENT", "Prepared + Ricochet", ["PREPARED", "RICOCHET", "FLICK_FLACK"], ["SWORD_OF_STONE", "SILVER_CRUCIBLE"], 20891),
        new("SILENT", "Leading Strike + Blade Dance", ["LEADING_STRIKE", "BLADE_DANCE", "CLOAK_AND_DAGGER"], ["SWORD_OF_STONE", "HEFTY_TABLET"], 20098),
        new("SILENT", "Deadly Poison + Poisoned Stab", ["DEADLY_POISON", "POISONED_STAB", "OUTBREAK"], ["SCROLL_BOXES", "SWORD_OF_STONE"], 14204),
        new("SILENT", "Phantom Blades + Blade of Ink", ["PHANTOM_BLADES", "BLADE_OF_INK", "ACCURACY"], ["TOUCH_OF_OROBAS", "JOSS_PAPER"], 12538),
        new("SILENT", "Knife Trap + Infinite Blades", ["KNIFE_TRAP", "INFINITE_BLADES", "BLADE_DANCE"], ["NUTRITIOUS_SOUP", "YUMMY_COOKIE"], 12309),
        new("SILENT", "Dagger Throw + Ricochet", ["DAGGER_THROW", "RICOCHET", "MEMENTO_MORI"], ["NUTRITIOUS_SOUP", "TOUCH_OF_OROBAS"], 11113),
        new("SILENT", "Accelerant + Bubble Bubble", ["ACCELERANT", "BUBBLE_BUBBLE", "MIRAGE"], ["SNECKO_SKULL", "TWISTED_FUNNEL"], 10854),
        new("SILENT", "Apparition + Reflex", ["APPARITION", "REFLEX", "ACROBATICS"], ["PRESERVED_FOG", "FRAGRANT_MUSHROOM"], 8112),
        new("SILENT", "Suppress + Tracking", ["SUPPRESS", "TRACKING", "BLADE_OF_INK"], ["ARCHAIC_TOOTH", "KUSARIGAMA"], 5908),
        new("SILENT", "Maul + Ultimate Strike", ["MAUL", "ULTIMATE_STRIKE", "KNIFE_TRAP"], ["CLAWS", "PRESERVED_FOG"], 5303),
        new("SILENT", "Nightmare + Skewer", ["NIGHTMARE", "SKEWER", "GRAND_FINALE"], ["PANDORAS_BOX", "JOSS_PAPER"], 3395),
        new("SILENT", "Nightmare + Afterimage", ["NIGHTMARE", "AFTERIMAGE", "ADRENALINE"], ["THE_COURIER", "NINJA_SCROLL"], 2431),
        new("DEFECT", "TURBO + Gunk Up", ["TURBO", "GUNK_UP", "REFRACT"], ["SWORD_OF_STONE", "PRECARIOUS_SHEARS"], 23295),
        new("DEFECT", "Ball Lightning + Lightning Rod", ["BALL_LIGHTNING", "LIGHTNING_ROD", "TESLA_COIL"], ["ARCHAIC_TOOTH", "SWORD_OF_STONE"], 15928),
        new("DEFECT", "Claw + Feral", ["CLAW", "FERAL", "SCRAPE"], ["SWORD_OF_STONE", "SCROLL_BOXES"], 13778),
        new("DEFECT", "Hailstorm + Quadcast", ["HAILSTORM", "QUADCAST", "SYNCHRONIZE"], ["ARCHAIC_TOOTH", "YUMMY_COOKIE"], 13691),
        new("DEFECT", "Smokestack + Gunk Up", ["SMOKESTACK", "GUNK_UP", "ROCKET_PUNCH"], ["MINIATURE_CANNON", "FESTIVE_POPPER"], 11526),
        new("DEFECT", "Thunder + Voltaic", ["THUNDER", "VOLTAIC", "STORM"], ["FRAGRANT_MUSHROOM", "ARCHAIC_TOOTH"], 10870),
        new("DEFECT", "Claw + Scrape", ["CLAW", "SCRAPE", "ALL_FOR_ONE"], ["FRAGRANT_MUSHROOM", "YUMMY_COOKIE"], 10571),
        new("DEFECT", "Ultimate Strike + Mad Science", ["ULTIMATE_STRIKE", "MAD_SCIENCE", "COMPILE_DRIVER"], ["BIIIG_HUG", "ASTROLABE"], 10414),
        new("DEFECT", "Tesla Coil + Thunder", ["TESLA_COIL", "THUNDER", "VOLTAIC"], ["TOUCH_OF_OROBAS", "LARGE_CAPSULE"], 3428),
        new("DEFECT", "Meteor Strike + Coolant", ["METEOR_STRIKE", "COOLANT", "HYPERBEAM"], ["PANDORAS_BOX", "MEAT_CLEAVER"], 3192),
        new("DEFECT", "Helix Drill + Meteor Strike", ["HELIX_DRILL", "METEOR_STRIKE", "REBOOT"], ["MEAT_CLEAVER", "EMOTION_CHIP"], 2735),
        new("DEFECT", "Voltaic + Ultimate Strike", ["VOLTAIC", "ULTIMATE_STRIKE", "MAD_SCIENCE"], ["TOUCH_OF_OROBAS", "FRAGRANT_MUSHROOM"], 2620),
        new("DEFECT", "Maul + Mad Science", ["MAUL", "MAD_SCIENCE", "BULK_UP"], ["CLAWS", "FRAGRANT_MUSHROOM"], 856),
        new("NECROBINDER", "Sow + Reap", ["SOW", "REAP", "PULL_AGGRO"], ["SWORD_OF_STONE", "PRECARIOUS_SHEARS"], 18907),
        new("NECROBINDER", "Defy + Sculpting Strike", ["DEFY", "SCULPTING_STRIKE", "VEILPIERCER"], ["HEFTY_TABLET", "SILVER_CRUCIBLE"], 13998),
        new("NECROBINDER", "Squeeze + Rattle", ["SQUEEZE", "RATTLE", "FLATTEN"], ["ARCHAIC_TOOTH", "BONE_FLUTE"], 11957),
        new("NECROBINDER", "Banshee's Cry + Pull from Below", ["BANSHEES_CRY", "PULL_FROM_BELOW", "MAD_SCIENCE"], ["FRAGRANT_MUSHROOM", "FAKE_HAPPY_FLOWER"], 11737),
        new("NECROBINDER", "Negative Pulse + Blight Strike", ["NEGATIVE_PULSE", "BLIGHT_STRIKE", "SOW"], ["SWORD_OF_STONE", "SCROLL_BOXES"], 11421),
        new("NECROBINDER", "Blight Strike + Scourge", ["BLIGHT_STRIKE", "SCOURGE", "TIMES_UP"], ["YUMMY_COOKIE", "PAELS_FLESH"], 10033),
        new("NECROBINDER", "Haunt + Soul Storm", ["HAUNT", "SOUL_STORM", "DEATH_MARCH"], ["ARCHAIC_TOOTH", "YUMMY_COOKIE"], 8826),
        new("NECROBINDER", "Sleight of Flesh + Deathbringer", ["SLEIGHT_OF_FLESH", "DEATHBRINGER", "DEATHS_DOOR"], ["FRAGRANT_MUSHROOM", "BOOK_REPAIR_KNIFE"], 8285),
        new("NECROBINDER", "Necro Mastery + Sentry Mode", ["NECRO_MASTERY", "SENTRY_MODE", "SQUEEZE"], ["TOUCH_OF_OROBAS", "BONE_FLUTE"], 5968),
        new("NECROBINDER", "Forbidden Grimoire + Eidolon", ["FORBIDDEN_GRIMOIRE", "EIDOLON", "SPIRIT_OF_ASH"], ["PANDORAS_BOX", "DUSTY_TOME"], 5200),
        new("NECROBINDER", "Shroud + Time's Up", ["SHROUD", "TIMES_UP", "DEATHS_DOOR"], ["PRESERVED_FOG", "MEAT_CLEAVER"], 4632),
        new("NECROBINDER", "Reap + Sow", ["REAP", "SOW", "DEFILE"], ["CURSED_PEARL", "NEOWS_BONES"], 4443),
        new("REGENT", "BEGONE! + Patter", ["BEGONE", "PATTER", "CELESTIAL_MIGHT"], ["SILKEN_TRESS", "SWORD_OF_STONE"], 24443),
        new("REGENT", "Knockout Blow + Solar Strike", ["KNOCKOUT_BLOW", "SOLAR_STRIKE", "CRESCENT_SPEAR"], ["SWORD_OF_STONE", "PRECARIOUS_SHEARS"], 16523),
        new("REGENT", "Refine Blade + Wrought in War", ["REFINE_BLADE", "WROUGHT_IN_WAR", "SPOILS_OF_BATTLE"], ["SWORD_OF_STONE", "SCROLL_BOXES"], 11464),
        new("REGENT", "Glow + Child of the Stars", ["GLOW", "CHILD_OF_THE_STARS", "PATTER"], ["YUMMY_COOKIE", "VERY_HOT_COCOA"], 11149),
        new("REGENT", "Crescent Spear + Black Hole", ["CRESCENT_SPEAR", "BLACK_HOLE", "DEVASTATE"], ["NUTRITIOUS_SOUP", "DUSTY_TOME"], 10390),
        new("REGENT", "Sword Sage + Parry", ["SWORD_SAGE", "PARRY", "SUMMON_FORTH"], ["FENCING_MANUAL", "FAKE_HAPPY_FLOWER"], 10157),
        new("REGENT", "Pillar of Creation + Supermassive", ["PILLAR_OF_CREATION", "SUPERMASSIVE", "ARSENAL"], ["REGALITE", "FRAGRANT_MUSHROOM"], 9014),
        new("REGENT", "The Sealed Throne + Mad Science", ["THE_SEALED_THRONE", "MAD_SCIENCE", "BIG_BANG"], ["SIGNET_RING", "SWORD_OF_JADE"], 6624),
        new("REGENT", "Maul + Ultimate Strike", ["MAUL", "ULTIMATE_STRIKE", "MAD_SCIENCE"], ["BIIIG_HUG", "ASTROLABE"], 6453),
        new("REGENT", "Seven Stars + Comet", ["SEVEN_STARS", "COMET", "NEUTRON_AEGIS"], ["TOUCH_OF_OROBAS", "STONE_CRACKER"], 4502),
        new("REGENT", "Arsenal + Monarch's Gaze", ["ARSENAL", "MONARCHS_GAZE", "HEIRLOOM_HAMMER"], ["PANDORAS_BOX", "MEAT_CLEAVER"], 4040),
        new("REGENT", "Meteor Shower + Furnace", ["METEOR_SHOWER", "FURNACE", "PARRY"], ["ARCHAIC_TOOTH", "LASTING_CANDY"], 3797),
        new("REGENT", "Meteor Shower + Mad Science", ["METEOR_SHOWER", "MAD_SCIENCE", "BIG_BANG"], ["ARCHAIC_TOOTH", "FRAGRANT_MUSHROOM"], 3246),
    ];
}
