namespace CoopBots.Building;

// GENERATED by scripts/import-spire-codex-resources.py from the Spire Codex snapshot.
// Do not edit by hand: re-run the script and let the coverage assertion in
// the test suite confirm every id still exists in this game build.
//
// Producers create a build's exclusive resource; payoffs are only worth
// their printed numbers when the deck can pay for it. Star consumption is
// the `star_cost` field rather than prose, which is why the two sides are
// extracted differently.
internal static class BakedResources
{
    internal sealed record Resource(string Name, string Label, string[] Owners, string[] Producers,
        string[] Multipliers, string[] Replayers, string[] Converters,
        string[] Spends);

    internal static readonly Resource[] All =
    [
        new("star", "Regent Stars", ["regent"], ["BIG_BANG", "BLACK_HOLE", "GATHER_LIGHT", "GENESIS", "GLOW", "HIDDEN_CACHE", "KNOCKOUT_BLOW", "ROYAL_GAMBLE", "SHINING_STRIKE", "SOLAR_STRIKE", "THE_SEALED_THRONE", "VENERATE"], [], [], ["ALIGNMENT", "ASTRAL_PULSE", "CLOAK_OF_STARS", "COMET", "CRESCENT_SPEAR", "DECISIONS_DECISIONS", "DEVASTATE", "DYING_STAR", "FALLING_STAR", "GAMMA_BLAST", "GUIDING_STAR", "METEOR_SHOWER", "NEUTRON_AEGIS", "PARTICLE_WALL", "QUASAR", "REFLECT", "RESONANCE", "SEVEN_STARS", "STARDUST", "THE_SMITH"], ["ALIGNMENT", "ASTRAL_PULSE", "CLOAK_OF_STARS", "COMET", "CRESCENT_SPEAR", "DECISIONS_DECISIONS", "DEVASTATE", "DYING_STAR", "FALLING_STAR", "GAMMA_BLAST", "GUIDING_STAR", "METEOR_SHOWER", "NEUTRON_AEGIS", "PARTICLE_WALL", "QUASAR", "REFLECT", "RESONANCE", "ROYAL_GAMBLE", "SEVEN_STARS", "STARDUST", "THE_SEALED_THRONE", "THE_SMITH"]),
        new("orb", "Defect orbs", ["defect"], ["BALL_LIGHTNING", "CHAOS", "CHILL", "COLD_SNAP", "CONSUMING_SHADOW", "COOLHEADED", "DARKNESS", "FUSION", "GLACIER", "GLASSWORK", "ICE_LANCE", "LIGHTNING_ROD", "METEOR_STRIKE", "NULL", "RAINBOW", "REFRACT", "SHADOW_SHIELD", "SPINNER", "STORM", "TRASH_TO_TREASURE", "ZAP"], [], ["VOLTAIC"], ["BARRAGE", "BULK_UP", "CAPACITOR", "COMPILE_DRIVER", "COOLANT", "DUALCAST", "IGNITION", "LOOP", "MODDED", "MULTI_CAST", "QUADCAST", "SHATTER", "SYNCHRONIZE", "TEMPEST", "THUNDER"], []),
        new("shiv", "Silent Shivs", ["silent"], ["BLADE_DANCE", "BLADE_OF_INK", "CLOAK_AND_DAGGER", "FAN_OF_KNIVES", "HIDDEN_DAGGERS", "INFINITE_BLADES", "LEADING_STRIKE", "STORM_OF_STEEL", "UP_MY_SLEEVE"], ["ACCURACY", "FAN_OF_KNIVES", "PHANTOM_BLADES"], ["KNIFE_TRAP"], [], []),
        new("poison", "Poison", ["silent"], ["BOUNCING_FLASK", "BUBBLE_BUBBLE", "CORROSIVE_WAVE", "DEADLY_POISON", "ENVENOM", "HAZE", "NOXIOUS_FUMES", "POISONED_STAB", "SNAKEBITE"], ["ACCELERANT"], [], ["MIRAGE"], []),
        new("doom", "Necrobinder Doom", ["necrobinder"], ["BLIGHT_STRIKE", "COUNTDOWN", "DEATHBRINGER", "END_OF_DAYS", "NEGATIVE_PULSE", "NEUROSURGE", "NO_ESCAPE", "OBLIVION", "REAPER_FORM", "SCOURGE", "SHROUD"], ["NO_ESCAPE"], [], ["DEATHS_DOOR", "SHROUD", "TIME'S UP", "TIMES_UP"], []),
        new("soul", "Necrobinder Souls", ["necrobinder"], ["CAPTURE_SPIRIT", "DIRGE", "GLIMPSE_BEYOND", "GRAVE_WARDEN", "REAVE", "SEVERANCE"], [], ["SOUL_STORM"], ["DEVOUR_LIFE", "HAUNT", "SEANCE"], []),
        new("focus", "Defect Focus (amplifier)", ["defect"], ["BIASED_COGNITION", "DEFRAGMENT", "FOCUSED_STRIKE", "HOTFIX", "SYNCHRONIZE"], [], [], ["HYPERBEAM"], []),
        new("strength", "Strength", ["colorless", "defect", "ironclad", "regent"], ["ARSENAL", "BRAND", "BULK_UP", "DEMON_FORM", "DOMINATE", "FIGHT_ME", "INFLAME", "MONOLOGUE", "PROWESS", "RESONANCE", "RUPTURE", "SETUP_STRIKE"], [], ["CONFLAGRATION", "DISMANTLE", "FIGHT_ME", "SPITE", "SWORD_BOOMERANG", "TEAR_ASUNDER", "THRASH", "TWIN_STRIKE", "WHIRLWIND"], ["COORDINATE", "CRUSH_UNDER", "DARK_SHACKLES", "DOMINATE", "DYING_STAR", "ENFEEBLING_TOUCH", "FRIENDSHIP", "MALAISE", "MANGLE", "MONARCHS_GAZE", "PIERCING_WAIL", "SHARED_FATE"], []),
        new("hp-loss", "Ironclad self-damage", ["ironclad"], ["BLOODLETTING", "BLOOD_WALL", "BRAND", "BREAKTHROUGH", "CRIMSON_MANTLE", "DEMONIC_SHIELD", "HEMOKINESIS", "INFERNO", "OFFERING"], [], [], ["RUPTURE"], []),
    ];
}
