#!/usr/bin/env python3
"""Bake the event option-id table into a C# file.

Source: https://spire-codex.com/api/events. Used under the PolyForm
Noncommercial 1.0.0 license and the Spire Codex API terms: free for community
use, attribution encouraged. Game data belongs to Mega Crit Games. See
THIRD_PARTY_NOTICES.md; the notice must ship with any release containing this.

Why this table exists: our per-event handlers match option *ids* (for example
REFLECTIONS...TOUCH_A_MIRROR). Nothing in the game stops an id being renamed by
a patch, and a handler whose id no longer matches fails silently — it looks
wired up but never fires. Baking the ids lets a test assert that every id a
handler refers to still exists.

Only ids are baked. Titles and descriptions are deliberately left out: they are
localized text, and our decisions must not depend on parsing them.

Usage:
    python scripts/import-spire-codex-events.py [input.json] [output.cs]
"""
import json
import os
import sys

DEFAULT_INPUT = "work/spire-codex/events.json"
DEFAULT_OUTPUT = "src/CoopBots/Building/BakedEvents.cs"
SOURCE = "https://spire-codex.com/api/events"


def csharp_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def option_ids(event: dict) -> list:
    """Every selectable id the event can show, across all of its pages."""
    ids = []
    for option in event.get("options") or []:
        if option.get("id"):
            ids.append(option["id"])
    for page in event.get("pages") or []:
        for option in page.get("options") or []:
            if option.get("id"):
                ids.append(option["id"])
    seen = set()
    unique = []
    for value in ids:
        if value in seen:
            continue
        seen.add(value)
        unique.append(value)
    return sorted(unique)


def main() -> int:
    source = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_INPUT
    target = sys.argv[2] if len(sys.argv) > 2 else DEFAULT_OUTPUT
    if not os.path.exists(source):
        print(f"error: {source} not found", file=sys.stderr)
        return 1
    with open(source, encoding="utf-8") as handle:
        events = json.load(handle)

    lines = [
        "// <auto-generated>",
        "//     Generated by scripts/import-spire-codex-events.py from",
        f"//     {SOURCE}",
        "//",
        "//     Source data: (c) 2025-present Peter Lord and Spire Codex contributors,",
        "//     used under the PolyForm Noncommercial License 1.0.0 and the Spire",
        "//     Codex API terms (community use, non-commercial, attribution",
        "//     encouraged). Slay the Spire 2 game data belongs to Mega Crit Games.",
        "//     See THIRD_PARTY_NOTICES.md. Do not edit by hand.",
        "//",
        "//     Option ids only: titles and descriptions are localized text and no",
        "//     decision may depend on parsing them.",
        "// </auto-generated>",
        "",
        "namespace CoopBots.Building;",
        "",
        "/// <summary>",
        "/// Every option id each event can show, across all of its pages. Used to",
        "/// check that the ids our handlers match still exist: a renamed id would",
        "/// otherwise leave a handler silently dead.",
        "/// </summary>",
        "internal static class BakedEvents",
        "{",
        f"    internal const string Source = {csharp_string(SOURCE)};",
        "",
        "    internal static readonly Dictionary<string, string[]> OptionIds = new(StringComparer.Ordinal)",
        "    {",
    ]
    count = 0
    for event in sorted(events, key=lambda e: e.get("id", "")):
        event_id = event.get("id")
        ids = option_ids(event)
        if not event_id or not ids:
            continue
        count += 1
        joined = ", ".join(csharp_string(value) for value in ids)
        lines.append(f"        [{csharp_string(event_id)}] = [{joined}],")
    lines += ["    };", "}", ""]

    os.makedirs(os.path.dirname(target), exist_ok=True)
    with open(target, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("\n".join(lines))
    print(f"wrote {target}: {count} events with option ids")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
