#!/usr/bin/env python3
"""Bake the data-mined archetype clusters into a C# table.

Source: https://spire-codex.com/api/runs/archetypes (see work/spire-codex/).
Used under the PolyForm Noncommercial 1.0.0 license and the Spire Codex API
terms: free for community use, attribution encouraged, game data belongs to
Mega Crit Games. The generated file carries the provenance and notice; the
notice in THIRD_PARTY_NOTICES.md must ship with any release containing it.

Only the cluster signature (defining cards/relics), its display name and its
sample size are baked. The reported win_rate is deliberately NOT used: the same
field reads as a percentage for some clusters and a small fraction for others,
so it cannot be weighted safely. Cluster membership is the durable signal and a
game patch only invalidates a signature by removing a card, which the
CoopBots test suite checks against the local build.

Usage:
    python scripts/import-spire-codex-archetypes.py [input.json] [output.cs]
"""
import json
import os
import sys

DEFAULT_INPUT = "work/spire-codex/archetypes.json"
DEFAULT_OUTPUT = "src/CoopBots/Building/BakedArchetypes.cs"
SOURCE = "https://spire-codex.com/api/runs/archetypes"


def csharp_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def csharp_array(values) -> str:
    return "[" + ", ".join(csharp_string(v) for v in values) + "]"


def main() -> int:
    source = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_INPUT
    target = sys.argv[2] if len(sys.argv) > 2 else DEFAULT_OUTPUT
    if not os.path.exists(source):
        print(f"error: {source} not found", file=sys.stderr)
        return 1
    with open(source, encoding="utf-8") as handle:
        data = json.load(handle)
    if not data.get("available"):
        print("error: the archetype feed reports unavailable", file=sys.stderr)
        return 1

    lines = [
        "// <auto-generated>",
        "//     Generated by scripts/import-spire-codex-archetypes.py from",
        f"//     {SOURCE}",
        f"//     snapshot built_at={data.get('built_at')}",
        "//",
        "//     Source data: (c) 2025-present Peter Lord and Spire Codex contributors,",
        "//     used under the PolyForm Noncommercial License 1.0.0 and the Spire",
        "//     Codex API terms (community use, non-commercial, attribution",
        "//     encouraged). Slay the Spire 2 game data belongs to Mega Crit Games.",
        "//     See THIRD_PARTY_NOTICES.md. Do not edit by hand.",
        "// </auto-generated>",
        "",
        "namespace CoopBots.Building;",
        "",
        "/// <summary>",
        "/// Archetype clusters mined from real runs, keyed by character. A cluster is",
        "/// its signature: the cards that most distinguish it. Nothing here is",
        "/// hand-authored, and the reported win rate is deliberately not carried",
        "/// over because its scale is not consistent between clusters.",
        "/// </summary>",
        "internal static class BakedArchetypes",
        "{",
        f"    internal const string Source = {csharp_string(SOURCE)};",
        f"    internal const string Snapshot = {csharp_string(str(data.get('built_at', '')))};",
        "",
        "    internal sealed record Cluster(string Character, string Name, string[] Cards, string[] Relics, int Size);",
        "",
        "    internal static readonly Cluster[] All =",
        "    [",
    ]

    count = 0
    for character, clusters in data.get("characters", {}).items():
        for cluster in sorted(clusters, key=lambda c: -c.get("size", 0)):
            cards = [c["id"] for c in cluster.get("defining_cards", []) if c.get("id")]
            relics = [r["id"] for r in cluster.get("defining_relics", []) if r.get("id")]
            if len(cards) < 2:
                continue  # A signature needs at least two cards to be detectable.
            count += 1
            lines.append(
                f"        new({csharp_string(character)}, {csharp_string(cluster.get('name', ''))}, "
                f"{csharp_array(cards)}, {csharp_array(relics)}, {int(cluster.get('size', 0))}),"
            )
    lines += ["    ];", "}", ""]

    os.makedirs(os.path.dirname(target), exist_ok=True)
    with open(target, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("\n".join(lines))
    print(f"wrote {target}: {count} clusters from {len(data.get('characters', {}))} characters")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
