#!/usr/bin/env python3
"""Bake per-card draft affinity (card-to-card synergy) into a C# table.

Source: https://spire-codex.com/api/draft-recs/cards/{id}, cached locally by
scripts/fetch-spire-codex-draft-recs.py. Used under the PolyForm Noncommercial
1.0.0 license and the Spire Codex API terms: free for community use,
attribution encouraged. Game data belongs to Mega Crit Games. See
THIRD_PARTY_NOTICES.md; the notice must ship with any release containing this.

What is baked, and what is thrown away:

* `lift` (preference / baseline preference) is the signal: how much more often
  two cards are taken together than chance. Unlike a raw win rate it is already
  normalised, so it does not simply reward cards that appear in good runs.
* Sample size decides whether a lift is trustworthy at all. A pair seen in six
  picks can show a lift above 2 by luck, so pairs below the floors below are
  dropped rather than shipped as a confident-looking number.
* `winrate` is not carried over: it is confounded by who picks what, which is
  the same reason the archetype feed's win rate is not used.

Usage:
    python scripts/import-spire-codex-affinity.py [cache-dir] [output.cs]
"""
import json
import os
import sys

DEFAULT_CACHE = "work/spire-codex/draft-recs"
DEFAULT_OUTPUT = "src/CoopBots/Building/BakedCardAffinity.cs"
LOCAL_IDS = "work/spire-codex/local-card-ids.txt"
SOURCE = "https://spire-codex.com/api/draft-recs/cards/{id}"

# A pair must have been offered and actually picked enough times to mean
# something. Chosen so the surviving pairs are the ones the data supports, not
# the long tail of coincidences.
MIN_OFFERS = 250
MIN_PICKS = 25
MIN_LIFT = 1.35
PARTNERS_PER_CARD = 4


def csharp_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def local_ids() -> set:
    """Ids the installed build actually has, written by the cross-check suite.

    The feed runs ahead of the game we build against, so it names cards this
    build does not know (for example SCARE). A reference that can never appear
    in a deck is dead weight, so it is dropped rather than shipped.
    """
    if not os.path.exists(LOCAL_IDS):
        print(f"warning: {LOCAL_IDS} not found; keeping every reference (run the "
              f"PatchSmoke suite once to write it)", file=sys.stderr)
        return set()
    with open(LOCAL_IDS, encoding="utf-8") as handle:
        return {line.strip() for line in handle if line.strip()}


def main() -> int:
    cache = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_CACHE
    target = sys.argv[2] if len(sys.argv) > 2 else DEFAULT_OUTPUT
    known = local_ids()
    if not os.path.isdir(cache):
        print(f"error: {cache} not found; run fetch-spire-codex-draft-recs.py first", file=sys.stderr)
        return 1

    pairs = {}
    snapshot = ""
    cards_seen = 0
    for name in sorted(os.listdir(cache)):
        if not name.endswith(".json"):
            continue
        with open(os.path.join(cache, name), encoding="utf-8") as handle:
            payload = json.load(handle)
        card_id = payload.get("item_id")
        if not card_id:
            continue
        cards_seen += 1
        snapshot = snapshot or str(payload.get("built_at", ""))
        kept = [
            partner for partner in payload.get("recommends") or []
            if partner.get("offers", 0) >= MIN_OFFERS
            and partner.get("picks", 0) >= MIN_PICKS
            and partner.get("lift", 0) >= MIN_LIFT
            and (not known or partner.get("id") in known)
        ]
        kept.sort(key=lambda partner: (-partner["lift"], -partner["picks"], partner["id"]))
        top = kept[:PARTNERS_PER_CARD]
        if top and (not known or card_id in known):
            pairs[card_id] = [(partner["id"], partner["lift"]) for partner in top]

    if not pairs:
        print("error: no pairs survived the sample floors", file=sys.stderr)
        return 1

    lines = [
        "// <auto-generated>",
        "//     Generated by scripts/import-spire-codex-affinity.py from",
        f"//     {SOURCE}",
        f"//     snapshot built_at={snapshot}",
        "//",
        "//     Source data: (c) 2025-present Peter Lord and Spire Codex contributors,",
        "//     used under the PolyForm Noncommercial License 1.0.0 and the Spire",
        "//     Codex API terms (community use, non-commercial, attribution",
        "//     encouraged). Slay the Spire 2 game data belongs to Mega Crit Games.",
        "//     See THIRD_PARTY_NOTICES.md. Do not edit by hand.",
        "// </auto-generated>",
        "",
        "namespace CoopBots.Building;",
        "",
        "/// <summary>",
        "/// Card-to-card draft affinity, mined from real picks. Each entry lists the",
        "/// cards that were taken alongside this one far more often than chance",
        "/// (lift), filtered to pairs with enough samples to be worth trusting.",
        "/// </summary>",
        "internal static class BakedCardAffinity",
        "{",
        f"    internal const string Source = {csharp_string(SOURCE)};",
        f"    internal const string Snapshot = {csharp_string(snapshot)};",
        f"    internal const int MinOffers = {MIN_OFFERS};",
        f"    internal const int MinPicks = {MIN_PICKS};",
        "",
        "    /// <summary>Partner card id to its lift, best first.</summary>",
        "    internal static readonly Dictionary<string, (string Card, double Lift)[]> Pairs = new(StringComparer.Ordinal)",
        "    {",
    ]
    for card_id in sorted(pairs):
        entries = ", ".join(f"({csharp_string(partner)}, {lift:.2f})" for partner, lift in pairs[card_id])
        lines.append(f"        [{csharp_string(card_id)}] = [{entries}],")
    lines += ["    };", "}", ""]

    os.makedirs(os.path.dirname(target), exist_ok=True)
    with open(target, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("\n".join(lines))
    total = sum(len(v) for v in pairs.values())
    dropped = "unfiltered" if not known else f"filtered to {len(known)} known ids"
    print(f"wrote {target}: {len(pairs)} cards, {total} pairs "
          f"(from {cards_seen} cached responses; floors offers>={MIN_OFFERS} picks>={MIN_PICKS} "
          f"lift>={MIN_LIFT}; {dropped})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
